### ISSUE TITLE
Authorize.net addon install fail with Composer

### ISSUE THREAD

**Issue by teknoziz** [concretecms-community-store/community_store_authorize_net#1]
As indicated in the summary at the bottom of the addon page, I went ahead and installed Composer on my Mac MAMP install of C5 in the community_store root directory. It downloaded and installed the composer.phar file successfully. Then I downloaded and attempted the install of the Authorize.net addon and received an error:

Concrete\Package\CommunityStoreAuthorizeNet\Controller::on_start(): Failed opening required 'vendor/autoload.php'

I read up on this file from the Composer site and I understand what it does, but since the install failed there is no such file and now my site won't load except to give me that error. Suggestions? I couldn't find a copy of the file to download from the Composer site, is it unique to each install?

**Comment by Mesuva** [comment]
This sounds like you've missed the step where you run composer against the add-on folder. 
It's not that composer is a prerequisite for install or running it, it's simply a tool used to help download the libraries within the package (and to keep them up to date while developing).

So for reference, you'd need to also run
```
composer install
```
as a command/terminal command against the package folder. When you do this, you'll see composer download some resources and you'll end up with these in a vendor folder (which then includes the autoload.php file)

However, you can skip all of that and simply download a 'release' of the add-on from https://github.com/concrete5-community-store/community_store_authorize_net/releases
This already has the libraries installed and ready to go, no need to use composer then.
