### ISSUE TITLE
Clicked install in my dashboard and it crashed my install

### ISSUE THREAD

**Issue by mdius** [concretecms-community-store/community_store_authorize_net#2]
http://www.mytinytown.com/

Is what I get now, I unzipped the package in my packages folder, removed -master and clicked install. Just like I did to install community_store.

**Comment by mdius** [comment]
I deleted the install and started over, if it happens again I'll post it here, if not I'll close this.

**Comment by mdius** [comment]
Yes, when I install it crashes my site. This time I put on debugging.

`Whoops \ Exception \ ErrorException (E_COMPILE_ERROR)
HELP
Concrete\Package\CommunityStoreAuthorizeNet\Controller::on_start(): Failed opening required '/home/tinytown/public_html/packages/community_store_authorize_net/vendor/autoload.php' (include_path='/home/tinytown/public_html/updates/concrete5.7.5.9_remote_updater/concrete/vendor:.:/opt/cpanel/ea-php56/root/usr/share/pear')`

`/home/tinytown/public_html/packages/community_store_authorize_net/controller.php
            $pkg = parent::install();
            $pm = new PaymentMethod();
            $pm->add('community_store_authorize_net','Authorize.Net',$pkg);
        }
    }
 
    public function on_start() {
        require __DIR__ . '/vendor/autoload.php';
    }
 `

**Comment by mdius** [comment]
I fixed the issue by removing this line:
`public function on_start() {
    require __DIR__ . '/vendor/autoload.php';
}`

**Comment by Mesuva** [comment]
This looks like you've downloaded the master branch and are trying to install that without running composer.

Instead, try downloading a 'release' of this package and installing that:
https://github.com/concrete5-community-store/community_store_authorize_net/releases

(make sure you read the notes in the Readme!)

**Comment by mdius** [comment]
Why thank you for that info. I am very new to github and had no idea. I've been using Vivid Store and needed something a little better.

Now I must ask, I downloaded the master to the main store, it installed fine, is this going to be a problem?
