### ISSUE TITLE
Include line item / product details on the generated Authorize.Net receipt

### ISSUE THREAD

**Issue by ebell14** [concretecms-community-store/community_store_authorize_net#3]
Authorize.net provides a generic automated email receipt when an order is completed, is there a way to include the product names in the authorize receipts?

**Comment by Mesuva** [comment]
I believe we can add additional data in, there are description and lineItem fields that can be passed in the createTransactionRequest XML that we aren't using right now:
https://developer.authorize.net/api/reference/

I think this then is a question of what shows up on the automatic email receipt, whether it shows just the description, or if you include all the line items do they show up as well (or maybe it shows both).

**Comment by ebell14** [comment]
I would expect the receipt to display the name of the product, any options that were selected and quantity so at a glance the person receiving the notification has a sense of what was ordered, the more descriptive the better.

**Comment by Mesuva** [comment]
I've pushed up commit https://github.com/concrete5-community-store/community_store_authorize_net/commit/e51aaddfdd76e7982467f71317686cdecca1437f to address this

**Comment by ebell14** [comment]
Hello Ryan,

I installed the update and bumped into this error message on attempting to checkout.

Product: I was testing a $1 donation 
Authorize.Net Payment Method - v1.0.2

Error: 
ErrorE00003The 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:unitPrice' element is invalid - The value &#39;&#39; is invalid according to its datatype 'Decimal' - The string &#39;&#39; is not a valid Decimal value.

**Comment by Mesuva** [comment]
Hi Eric,

I think I’ve chased this one down - fix is this commit here:
https://github.com/concrete5-community-store/community_store_authorize_net/commit/0c0aecbdb4f60a8a83200c82e513e35d3e388c1e <https://github.com/concrete5-community-store/community_store_authorize_net/commit/0c0aecbdb4f60a8a83200c82e513e35d3e388c1e>

What it was is that when it’s a customer supplied price, the function that normally fetches the product price returns blank (which makes sense), and it had to look elsewhere to find it.
I’ve been able to put through a transaction with a custom price earlier now. Also found another bug to do with title lengths.

How horrible is Authorise.net’s admin by the way - I struggled to get it working again!

Let me know how you go with this one, it should be the case of replacing the one file CommunityStoreAuthorizeNetPaymentMethod.php

**Comment by ebell14** [comment]
Thanks Ryan that worked, for as big of a company as Authorize.net their systems are clunky and a bit outdated for sure.
