### ISSUE TITLE
When purchase order using authorize_net get this error 

### ISSUE THREAD

**Issue by ghost** [concretecms-community-store/community_store_authorize_net#4]
﻿ErrorE00003'…' is an unexpected token. The expected token is ';'. Line 16, position 85.

Why this error is occur? Have Any Solving.

**Comment by Mesuva** [comment]
ErrorE00003 appears to be an error returned from Authorize.net, and not a PHP error.

Can you see anything in Authorize.net's transaction log that gives more detail as to what is going wrong?

**Comment by ghost** [comment]
Sorry for the late response ..
The Isssue Was Because of the lenght of the product name was larger .so reduce the name fixed it.
